### PR TITLE
Revision 0819

### PR DESCRIPTION
**Pull request by Chiloven945**
@tangge233 @3gf8jv4dv

### CODE REVIEW

**Comment by Chiloven945** [comment]
@tangge233 merge this.

**Comment by Chiloven945** [comment]
Don't merge yet, there are still some new strings(

**Comment by Chiloven945** [comment]
@3gf8jv4dv @tangge233

**Comment by Chiloven945** [comment]
Merge

**Review by tangge233 — APPROVED** [review]

**Pull request merged**
