### PR TITLE
Translation Revision & Keys Spelling Check

### PR DESCRIPTION
**Pull request by Chiloven945**
@tangge233 @3gf8jv4dv

### CODE REVIEW

**Comment by Chiloven945** [comment]
> For some `.jar` or `jar` terms, the same key may be uppercase in some languages ​​and lowercase in others. Of course, this does not apply to the terminology used for parts of a file name.

I'll check it later.

**Comment by Chiloven945** [comment]
@3gf8jv4dv How about now?

**Comment by Chiloven945** [comment]
@tangge233 Merge this pr if no more advice available.

**Comment by tangge233** [comment]
There are some conflicts…

**Pull request merged**
