### PR TITLE
Translation Terms Overhaul for zh_TW

### PR DESCRIPTION
**Pull request by Chiloven945**
Some overhaul for zh_TW to improve the l10n, advice and assistance are welcome.
If this is the language that you originally speak, **PLEASE** help us to improve it further.
一些對於zh_TW的修改，著重於用語方面。歡迎提出建議和進行協助。
如果您以此語言為母語，**懇請您**幫助我們以進一步完善並改進它。

### CODE REVIEW

**Comment by Chiloven945** [comment]
Just a mention, if using zh_TW, the font `Microsoft YaHei` needs to be changed to `Microsoft JhengHei` for the font adaption.

**Comment by Chiloven945** [comment]
I'll comment at there.

**Comment by Chiloven945** [comment]
Should we keep the names of people as simplified characters or just transform them to traditional characters?
Like `龙腾猫跃` -> `龍騰貓躍`.

**Comment by tangge233** [comment]
可以合并了么?
Is it ready to be merged?

**Comment by Chiloven945** [comment]
For me is yes.

**Pull request merged**
